export const projects = [
  {
    title: 'Pharmacology',
    description: "An android app for Delta State University Students, (Nigeria). Contains an e-commerce section and a news section ",
      image: '/images/project/cology.jpg',
      tags: ['Dart', 'Flutter', 'Firebase', ],
    source: '/cology',
    visit: '/courses/cology',
    id: 0,
  },
  {
    title: 'Pharmaceutics',
    description:"Mobile Inventory Management System. An android app to track inventory of a retail shop.",
    image: '/images/project/ceutics.jpg',
    tags: ['Dart', 'Flutter', 'Firebase', ],
    source: '#',
    visit: '#',
    id: 1,
  },
  {
    title: 'Clinical Pharmacy',
    description: "An Educaational App for Pharmacists preparing for various exams.",
      image: '/images/project/clinic.jpg',
      tags: ['Dart', 'Flutter', 'Firebase', ],
    source: 'https://play.google.com/store/apps/details?id=com.philix.rxedu',
    visit: 'https://play.google.com/store/apps/details?id=com.philix.rxedu',
    id: 2,
  },
  {
    title: 'Pharmacognosy',
    description: "An Educaational Website (For the app) for Pharmacists preparing for various exams.",
      image: '/images/project/cognosy.jpg',
      tags: ['React', 'Next.js', 'Node js',],
    source: 'rxedu.online',
    visit: 'rxedu.online',
    id: 2,
  },
  {
    title: 'Pharmaceutical Microbiology',
    description: "An Educaational Website (For the app) for Pharmacists preparing for various exams.",
      image: '/images/project/micro.jpg',
      tags: ['React', 'Next.js', 'Node js',],
    source: 'rxedu.online',
    visit: 'rxedu.online',
    id: 2,
  },
  {
    title: 'Pharmaceutical Chemistry',
    description: "An Educaational Website (For the app) for Pharmacists preparing for various exams.",
      image: '/images/project/chem.jpg',
      tags: ['React', 'Next.js', 'Node js',],
    source: 'rxedu.online',
    visit: 'rxedu.online',
    id: 2,
  },
  
];
